### ISSUE TITLE
Leaving the imported file in place

### ISSUE THREAD

**Issue by Hunter-Github** [Phyks/BMC#24]
Is it possible to add an option to leave the file where it currently is?

**Comment by Phyks** [comment]
:+1: I will handle it as soon as I can.

**Comment by Phyks** [comment]
@Hunter-Github hmm, what would be the exact expected behaviour?

File is left where it currently is, but what about the Bibtex index? Still generated in a `~/Papers` folder?

**Comment by Hunter-Github** [comment]
Yes, that's the preferred behavior - a central autofilled bib database was  my longstanding daydream ))

**Comment by Phyks** [comment]
@Hunter-Github Should be ok with a `--in-place` parameter, for the `import` action. This is implemented in the `issue24` branch, waiting for your feedback to be merged :)

**Comment by Hunter-Github** [comment]
Two things to consider:

* the switch is enabled for the `download` command;
* after changing bmc.py to link the switch to `import`, importing adds the file to `~/Papers` which it shouldn't.

**Comment by Phyks** [comment]
Sorry, there was a remaining bug. Should be ok by now.

**Comment by Hunter-Github** [comment]
Leaves the file in place but the `file` field shows relative path (that is the path that was a command-line argument), would be better if absolute filepaths were kept.

**Comment by Phyks** [comment]
Indeed. Should be fixed.

**Comment by Hunter-Github** [comment]
The most recent https://github.com/Phyks/BMC/commit/84a7a1cd63a7fb51551ce29dba4f19a79e896486 works fine.

One more thing to consider - if the file has been imported in-place, the `delete` command unlinks it. I can open a new issue to discuss the behavior.
