### ISSUE TITLE
bmc.py list doesn't list files that have been imported in-place

### ISSUE THREAD

**Issue by Hunter-Github** [Phyks/BMC#25]
https://github.com/Phyks/BMC/commit/84a7a1cd63a7fb51551ce29dba4f19a79e896486 : `list` command doesn't output paths to files outside the `~/Papers` directory.

**Comment by Phyks** [comment]
Indeed, config is listing the content of the `~/Papers` dir. It should list the content of the `index.bib` instead. Will fix it.

**Comment by Phyks** [comment]
Fixed. Now list only the files from the `index.bib`.
