### ISSUE TITLE
Discussion: what should be the `delete` behavior?

### ISSUE THREAD

**Issue by Hunter-Github** [Phyks/BMC#26]
* For a file in `Papers` 

 * Remove the citation from `index.bib` and unlink the file (**currently used**, _most logical_);
 * Remove the citation, do not unlink the file (not logical at all).

* For a file imported in-place:

 * Remove from index, unlink (**current behavior**, somewhat objectionable)
 * Remove from index, leave in-place (not implemented).

The user should be forewarned that some operations are a) irreversible and/or b) not idempotent, IMHO. An alternative - give the `delete` command an `-m/manual`  switch to signify no unlinking is to take place. Another, perhaps more usable alternative, do not unlink by default.

**Comment by Phyks** [comment]
I'd rather go for a param to keep the file on deletion. It is the simplest and most logical way I can think of. But I am open to discussion :)

**Comment by Hunter-Github** [comment]
A parameter `--keep` would be fine. Thanks for the great program, I'm really putting my files in order now.

**Comment by Phyks** [comment]
@Hunter-Github should be done on last commit. However, I do not have my machine with me to test it… Will test it later and debug if not working. Let me know if you can test and find any problems. Thanks!

P.S.: Happy to see you enjoy the script =D
