### ISSUE TITLE
bmc.py KeyError

### ISSUE THREAD

**Issue by berceanu** [Phyks/BMC#31]
'bmc.py download http://arxiv.org/pdf/1412.3638v2'

'''
Downloading http://arxiv.org/pdf/1412.3638v2
[==================================================] 96%Download finished
ArXiv id for /tmp/tmpbwpxkzwh.pdf is 1412.3638v2.
Traceback (most recent call last):
  File "/usr/bin/bmc.py", line 568, in <module>
    args.tag)
  File "/usr/bin/bmc.py", line 300, in downloadFile
    new_name = addFile(tmp.name, filetype, manual, autoconfirm, tag)
  File "/usr/bin/bmc.py", line 173, in addFile
    bibtex = fetcher.arXiv2Bib(arxiv).strip().replace(',', ",\n")+"\n"
  File "/usr/lib/python3.5/site-packages/libbmc/fetcher.py", line 323, in arXiv2Bib
    return tools.parsed2Bibtex(fetched_bibtex)
  File "/usr/lib/python3.5/site-packages/libbmc/tools.py", line 49, in parsed2Bibtex
    bibtex = '@'+parsed['type']+'{'+parsed['id']+",\n"
KeyError: 'type'
'''

**Comment by Phyks** [comment]
You are not up to date. This is issue #30 which should be solved in the up to date master branch.

**Comment by berceanu** [comment]
I am using https://aur4.archlinux.org/packages/bmc

**Comment by Phyks** [comment]
Just flagged the package as out of date on AUR as I am not maintaining it.

**Comment by sciunto** [comment]
The package on aur is up to date. The last release I see on github is 0.5. #30 happened after this release.

**Comment by Phyks** [comment]
Actually there was a non backward compatible change in python-bibtexparser so the air package should depend on this previous version.  

I'm sorry I did not flag a new version after the bug fix, was sure I did. I will add a new tag asap.

**Comment by sciunto** [comment]
aur has be updated. Thx.

**Comment by Phyks** [comment]
Awesome! Thanks!
