### ISSUE TITLE
Unable to open index file

### ISSUE THREAD

**Issue by LuisBL** [Phyks/BMC#32]
from a fresh today install I get 

    $ bmc.py list 
    WARNING:  Unable to open index file.
    $ 

idem for resync::

    $ bmc.py resync
    Resync files and bibtex index? [y/N] y
    WARNING:  Unable to open index file.
    $

**Comment by Phyks** [comment]
By “clean install” does it mean you used `bmc.py list` before actually importing any articles? It could explain the issue, and I will try to solve it.

If this is the case, can you confirm me that you can import papers?

Other things to check:
* `~/.config/bmc/bmc.json` is a valid JSON file with a correct path for "folder".
* `~/Papers` (or whatever path is in `folder` in the previous JSON file) is a valid existing directory, and the script can write into it.

Thanks

**Comment by Phyks** [comment]
Closing as lacking info to work on it. Feel free to comment and reopen if you are still experiencing issues.
